// JavaScript Document

(function(){
var info = ''
+ '<nav class="navbar navbar-fixed-top">'
+ '	<div class="container">'
+ '		<div class="navbar-header">'
+ '			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">'
+ '				<span class="sr-only">Toggle navigation</span>'
+ '				<span class="icon-bar"></span>'
+ '				<span class="icon-bar"></span>'
+ '				<span class="icon-bar"></span>'
+ '			</button>'
+ '			<a class="navbar-brand" href="index.html"><img src="imgs/site-logo.png" alt="Clint Naugle"></a>'
+ '		</div>'
+ '		<div id="navbar" class="collapse navbar-collapse">'
+ '     	<ul class="nav navbar-nav">'
+ '				<li>'
+ '					<div class="dropdown">'
+ '						<button class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Responsive <span class="caret"></span></button>'
+ '						<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">'
+ '	    						<li><a href="rwd-01.html">Vendor Template</a></li>'
+ '	    						<li><a href="rwd-02.html">Windows 10</a></li>'
+ '	  							<li><a href="rwd-03.html">Facebook Deals</a></li>'
+ '	    						<li><a href="rwd-04.html">Samsung 850 Pro</a></li>'
+ '	  						</ul>'
+ '						</div>'
+ '				</li>'
+ '				<li>'
+ '					<div class="dropdown">'
+ '						<button class="dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">E-Commerce <span class="caret"></span></button>'
+ '						<ul class="dropdown-menu" aria-labelledby="dropdownMenu2">'
+ '	    						<li><a href="ecommerce-01.html">Banner Design</a></li>'
+ '	    						<li><a href="ecommerce-02.html">Black Friday</a></li>'
+ '	  							<li><a href="ecommerce-03.html">May the 4th</a></li>'
+ '	    						<li><a href="ecommerce-04.html">JR.com Redesign</a></li>'
+ '	  						</ul>'
+ '						</div>'
+ '				</li>'
+ '				<li>'
+ '					<div class="dropdown">'
+ '						<button class="dropdown-toggle" type="button" id="dropdownMenu3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Print <span class="caret"></span></button>'
+ '						<ul class="dropdown-menu" aria-labelledby="dropdownMenu3">'
+ '	    						<li><a href="print-01.html">Newegg Credit Card</a></li>'
+ '	    						<li><a href="print-02.html">J&amp;R Branding and Signage</a></li>'
+ '	  							<li><a href="print-03.html">J&amp;R Vector Set</a></li>'
+ '	  						</ul>'
+ '						</div>'
+ '				</li>'
+ '				<li><a href="pdf/resume-clint-naugle.pdf" target="_pdf">Resume</a></li>'
+ '			</ul>'
+ '		</div><!--/.nav-collapse -->'
+ '	</div>'
+ '</nav>'
+ ''
document.write(info);
})();