(function(){
var info = ''
+ '<footer class="footer">'
+ '	<div class="footer-inner">'
+ '		<p class="footer-text">Looking for special offers, coupon codes, and exclusive promotions? Subscribe to the Newegg.com Newsletter</p>'
+ '		<div class="subscribe-area">'
+ '			<form action="#" method="post" name="Newsletter">'
+ '             <input class="form-input form-input-mini" placeholder="Enter Your Email Address" type="email">'
+ '             <input type="submit" class="btn btn-mini btn-primary" value="Subscribe"></input>'
+ '         </form>'
+ '		</div>'
+ '		<ul class="social-follow-list">'
+ '			<li class="social-follow-item">'
+ '				<a target="_blank" href="#g" title="Facebook Newegg" class="fa fa-facebook social-follow-item-icon"></a>'
+ '			</li>'
+ '			<li class="social-follow-item">'
+ '				<a target="_blank" href="#" title="Twitter @Newegg" class="fa fa-twitter social-follow-item-icon"></a>'
+ '			</li>'
+ '			<li class="social-follow-item">'
+ '				<a target="_blank" href="#" title="Instagram Newegg" class="fa fa-instagram social-follow-item-icon"></a>'
+ '			</li>'
+ '			<li class="social-follow-item">'
+ '				<a target="_blank" href="#" title="Google+ Newegg" class="fa fa-google-plus social-follow-item-icon"></a>'
+ '			</li>'
+ '			<li class="social-follow-item">'
+ '				<a target="_blank" href="#" title="Pinterest Newegg" class="fa fa-pinterest social-follow-item-icon"></a>'
+ '			</li>'
+ '			<li class="social-follow-item">'
+ '				<a target="_blank" href="#" title="Youtube NeweggTV" class="fa fa-youtube-play social-follow-item-icon"></a>'
+ '			</li>'
+ '		</ul>'
+ '		<p class="footer-text"><a href="#">Policy &amp; Agreement</a> | <a href="#">Privacy Policy</a> <span class="copyright"><i class="fa fa-copyright"></i> 2000-2016 Newegg Inc. All rights reserved.</span></p>'
+ '	</div>'
+ '</footer>'
+ ''
document.write(info);
})();